### ISSUE TITLE
Angular Start Up

### ISSUE THREAD

**Issue by dmartingarcia** [dmartingarcia/Sense#6]
**ARQUITECTURA**

Tal y como hablamos ayer @davidvilla y yo, el proyecto estará formado por diferentes microservicios.

En los proximos dias colgare diferentes esquemas del sistema mostrando en detalle el funcionamiento y las distintas partes que conforman el proyecto.

El fin de esta tarea es definir las diferentes partes a desarrollar así como sus propiedades y especificaciones mínimas, para así en un futuro poder seguir el modelo aquí discutido y tener en todo momento un sitio de consulta ademas de un lugar para discutir y revisar la especificación.

Finalmente se comparara el resultado final con el especificado aqui.

Hablamos en los proximos dias, pondre diagramas y diversas ideas.

cc/ @davidvilla @MariaJoseSantofimia

**Comment by basestylo** [comment]
PD: Se aceptan nombres para el proyecto, yo le llamo sense para aclararme entre los otros proyectos que tengo.
